[workspace]

members = [
    "auditors",
    "audits",
    "customers",
    "common",
    "files",
    "users",
    "search",
    "mail",
    "notification",
    "telemetry",
    "event",
    "report",
    "chat",
    "cloc",
]
