
x-common-variables: &common-variables
  MONGOURI: "mongodb://${MONGO_LOGIN}:${MONGO_PASSWORD}@dev-database:27017/?authSource=admin"
  JWT_SECRET: "${JWT_SECRET}"
  HELLO_MAIL_ADDRESS: "${HELLO_MAIL_ADDRESS}"
  HELLO_MAIL_PASSWORD: "${HELLO_MAIL_PASSWORD}"
  ADMIN_CREATION_PASSWORD: "${ADMIN_CREATION_PASSWORD}"
  AUDITORS_SERVICE_URL: "${AUDITORS_SERVICE_URL}"
  AUDITS_SERVICE_URL: "${AUDITS_SERVICE_URL}"
  CUSTOMERS_SERVICE_URL: "${CUSTOMERS_SERVICE_URL}"
  FILES_SERVICE_URL: "${FILES_SERVICE_URL}"
  MAIL_SERVICE_URL: "${MAIL_SERVICE_URL}"
  SEARCH_SERVICE_URL: "${SEARCH_SERVICE_URL}"
  USERS_SERVICE_URL: "${USERS_SERVICE_URL}"
  RENDERER_SERVICE_URL: "${RENDERER_SERVICE_URL}"
  NOTIFICATIONS_SERVICE_URL: "${NOTIFICATIONS_SERVICE_URL}"
  EVENTS_SERVICE_URL: "${EVENTS_SERVICE_URL}"
  FRONTEND: "${FRONTEND}"
  PROTOCOL: "${PROTOCOL}"
  FEEDBACK_EMAIL: "${FEEDBACK_EMAIL}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
  RUST_LOG: actix=info,reqwest=info,search=info,common=info,audits=trace
  TIMEOUT: "60"



services:
  dev-binaries:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - dev-binaries:/data/binaries

  dev-users:
    depends_on:
      - dev-binaries
    build: ./users
    ports:
      - 3001
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(user|auth|my_user|waiting_list)
      <<: *common-variables
    networks:
      - dev-database
      - dev-nginx-proxy

  dev-customers:
    depends_on:
      - dev-binaries
    build: ./customers
    ports:
      - 3002
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(customer|my_customer|project|my_project)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-audits:
    depends_on:
      - dev-binaries
    build: ./audits
    volumes:
      - dev-binaries:/data/binaries
    ports:
      - 3003
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(audit|my_audit|request|my_request|public_audits|no_customer_audit)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-auditors:
    depends_on:
      - dev-binaries
    build: ./auditors
    ports:
      - 3004
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(auditor|my_auditor|badge)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-files:
    depends_on:
      - dev-binaries
    build: ./files
    ports:
      - 3005
    volumes:
      - dev-binaries:/data/binaries
      - dev-files:/auditdb-files
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(file|notused1)
      <<: *common-variables
    networks:
      - dev-database
      - dev-nginx-proxy

  dev-search:
    depends_on:
      - dev-binaries
    build: ./search
    ports:
      - 3006
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(search|notused1)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-mail:
    depends_on:
      - dev-binaries
    build: ./mail
    ports:
      - 3007
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(mail|feedback|code)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-notification:
    depends_on:
      - dev-binaries
    build: ./notification
    ports:
      - 3008
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(send_notification|read_notification|unread_notifications)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-telemetry:
    depends_on:
      - dev-binaries
    build: ./telemetry
    ports:
      - 3009
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(telemetry|not_used1)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-chat:
    depends_on:
      - dev-binaries
    build: ./chat
    ports:
      - 3012
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(chat|not_used1)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-database

  dev-event:
    depends_on:
      - dev-binaries
    build: ./event
    ports:
      - 3010
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(notifications|event)
      <<: *common-variables
    networks:
      - dev-nginx-proxy

  dev-renderer:
    build:
      context: renderer
      dockerfile: Dockerfile
    ports:
      - 3015
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(generate-report|notused2)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-report

  dev-report:
    build: ./report
    depends_on:
      - dev-binaries
      - dev-renderer
    ports:
      - 3011
    volumes:
      - dev-binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(report|notused2)
      <<: *common-variables
    networks:
      - dev-nginx-proxy
      - dev-report

  dev-database:
    build: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=kletska2002
    ports:
      - 27017:27017
    volumes:
      - dev-database:/data/db
      - dev-database:/mongo_backup
    networks:
      - dev-database
volumes:
  dev-database:
  dev-backup:
  dev-files:
  dev-binaries:
networks:
  dev-report:
  dev-database:
  dev-nginx-proxy: