version: "3.8"

services:
  binaries:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    volumes:
      - binaries:/data/binaries
  users:
    depends_on:
      - binaries
    build: ./users
    ports:
      - 3001:3001
    volumes:
      - binaries:/data/binaries
    environment:
      MONGOURI: mongodb://database/backend
      MONGOURI_TEST: mongodb://database/test
      RUST_LOG: actix
      HELLO_MAIL_ADDRESS: "${HELLO_MAIL_ADDRESS}"
      HELLO_MAIL_PASSWORD: "${HELLO_MAIL_PASSWORD}"
  swagger:
    depends_on:
      - binaries
    build: ./swagger
    ports:
      - 8080:8080
    volumes:
      - binaries:/data/binaries
    environment:
      MONGOURI: mongodb://database/backend
      MONGOURI_TEST: mongodb://database/test
      RUST_LOG: actix
  customers:
    depends_on:
      - binaries
    build: ./customers
    ports:
      - 3003:3002
    volumes:
      - binaries:/data/binaries
    environment:
      MONGOURI: mongodb://database/backend
      MONGOURI_TEST: mongodb://database/test
      RUST_LOG: actix
  audits:
    depends_on:
      - binaries
    build: ./audits
    volumes:
      - binaries:/data/binaries
    ports:
      - 3004:3003
    environment:
      MONGOURI: mongodb://database/backend
      MONGOURI_TEST: mongodb://database/test
      RUST_LOG: trace
  auditors:
    depends_on:
      - binaries
    build: ./auditors
    ports:
      - 3002:3004
    volumes:
      - binaries:/data/binaries
    environment:
      MONGOURI: mongodb://database/backend
      MONGOURI_TEST: mongodb://database/test
      RUST_LOG: actix
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

volumes:
  database:
  binaries:
