
x-common-variables: &common-variables
  MONGOURI: "mongodb://${MONGO_LOGIN}:${MONGO_PASSWORD}@database:27017"
  JWT_SECRET: "${JWT_SECRET}"
  HELLO_MAIL_ADDRESS: "${HELLO_MAIL_ADDRESS}"
  HELLO_MAIL_PASSWORD: "${HELLO_MAIL_PASSWORD}"
  ADMIN_CREATION_PASSWORD: "${ADMIN_CREATION_PASSWORD}"
  AUDITORS_SERVICE_URL: "${AUDITORS_SERVICE_URL}"
  AUDITS_SERVICE_URL: "${AUDITS_SERVICE_URL}"
  CUSTOMERS_SERVICE_URL: "${CUSTOMERS_SERVICE_URL}"
  FILES_SERVICE_URL: "${FILES_SERVICE_URL}"
  MAIL_SERVICE_URL: "${MAIL_SERVICE_URL}"
  SEARCH_SERVICE_URL: "${SEARCH_SERVICE_URL}"
  USERS_SERVICE_URL: "${USERS_SERVICE_URL}"
  NOTIFICATIONS_SERVICE_URL: "${NOTIFICATIONS_SERVICE_URL}"
  EVENTS_SERVICE_URL: "${EVENTS_SERVICE_URL}"
  FRONTEND: "${FRONTEND}"
  PROTOCOL: "${PROTOCOL}"
  FEEDBACK_EMAIL: "${FEEDBACK_EMAIL}"
  RUST_LOG: actix=info,reqwest=info,search=info,common=info
  TIMEOUT: "60"



services:
  binaries:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - binaries:/data/binaries

  users:
    depends_on:
      - binaries
    build: ./users
    expose:
      - 3001
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(user|auth|my_user|waiting_list)
      <<: *common-variables
    networks:
      - database
      - nginx-proxy

  customers:
    depends_on:
      - binaries
    build: ./customers
    expose:
      - 3002
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(customer|my_customer|project|my_project)
      <<: *common-variables
    networks:
      - nginx-proxy
      - database

  audits:
    depends_on:
      - binaries
    build: ./audits
    volumes:
      - binaries:/data/binaries
    ports:
      - 3003
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(audit|my_audit|request|my_request|public_audits)
      <<: *common-variables
    networks:
      - nginx-proxy
      - database

  auditors:
    depends_on:
      - binaries
    build: ./auditors
    expose:
      - 3004
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(auditor|my_auditor)
      <<: *common-variables
    networks:
      - nginx-proxy
      - database

  files:
    depends_on:
      - binaries
    build: ./files
    expose:
      - 3005
    volumes:
      - binaries:/data/binaries
      - files:/auditdb-files
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(file|notused1)
      <<: *common-variables
    networks:
      - database
      - nginx-proxy

  search:
    depends_on:
      - binaries
    build: ./search
    expose:
      - 3006
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(search|notused1)
      <<: *common-variables
    networks:
      - nginx-proxy
      - database

  mail:
    depends_on:
      - binaries
    build: ./mail
    expose:
      - 3007
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(mail|feedback)
      <<: *common-variables
    networks:
      - nginx-proxy
      - database

  notification:
    depends_on:
      - binaries
    build: ./notification
    expose:
      - 3008
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(send_notification|read_notification|unread_notifications)
      <<: *common-variables
    networks:
      - nginx-proxy
      - database

  event:
    depends_on:
      - binaries
    build: ./event
    expose:
      - 3010
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: dev.auditdb.io
      VIRTUAL_PATH: ~^/api/(notifications|event)
      <<: *common-variables
    networks:
      - nginx-proxy

  renderer:
    build:
      context: ./renderer
      dockerfile: ./renderer/Dockerfile
    expose:
      - 8080
    networks:
      - report

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=kletska2002
    ports:
      - 27017:27017
    volumes:
      - test:/data/db
    networks:
      - database
volumes:
  database:
  binaries:
  files:
  test:
networks:
  report:
  database:
  nginx-proxy:
    external:
      true

