version: "3.8"

services:
  binaries:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - binaries:/data/binaries
  users:
    depends_on:
      - binaries
    build: ./users
    expose:
      - "3001"
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: auditdb.io
      VIRTUAL_PATH: ~^/api/(users|auth|waiting_list)
      MONGOURI: mongodb://database/backend
      RUST_LOG: actix
      HELLO_MAIL_ADDRESS: "${HELLO_MAIL_ADDRESS}"
      HELLO_MAIL_PASSWORD: "${HELLO_MAIL_PASSWORD}"
    networks:
      - nginx-proxy
      - database
  swagger:
    depends_on:
      - binaries
    build: ./swagger
    expose:
      - "8080"
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: auditdb.io
      VIRTUAL_PATH: ~^/(swagger-ui|api-doc)/
      MONGOURI: mongodb://database/backend
      RUST_LOG: actix
    networks:
      - nginx-proxy
  customers:
    depends_on:
      - binaries
    build: ./customers
    expose:
      - "3002"
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: auditdb.io
      VIRTUAL_PATH: ~^/api/(customer|projects)
      MONGOURI: mongodb://database/backend
      RUST_LOG: actix
    networks:
      - nginx-proxy
      - database
  audits:
    depends_on:
      - binaries
    build: ./audits
    volumes:
      - binaries:/data/binaries
    expose:
      - "3003"
    environment:
      VIRTUAL_HOST: auditdb.io
      VIRTUAL_PATH: ~^/api/(audit|requests)
      MONGOURI: mongodb://database/backend
      RUST_LOG: "actix,audit"
    networks:
      - nginx-proxy
      - database
  auditors:
    depends_on:
      - binaries
    build: ./auditors
    expose:
      - "3004"
    volumes:
      - binaries:/data/binaries
    environment:
      VIRTUAL_HOST: auditdb.io
      VIRTUAL_PATH: ~^/api/(auditor|notused2)
      MONGOURI: mongodb://database/backend
      RUST_LOG: actix
    networks:
      - nginx-proxy
      - database
  files:
    depends_on:
      - binaries
    build: ./files
    expose:
      - "3005"
    volumes:
      - binaries:/data/binaries
      - files:/auditdb-files
    environment:
      VIRTUAL_HOST: auditdb.io
      VIRTUAL_PATH: ~^/api/(files|notused1)
      MONGOURI: mongodb://database/backend
      RUST_LOG: actix
    networks:
      - nginx-proxy
      - database
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    networks:
      - database

volumes:
  database:
  binaries:
  files:
networks:
  nginx-proxy:
    external: true
  database:

