version: "3.8"

services:
  backedend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3004:3004
      - 4001:4001
    environment:
      MONGOURI: mongodb://database/backend
      RUST_LOG: actix
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - backend:/data/db

volumes:
  backend:
