export const PLAIN_TEXT = 'plain_text'
export const PROJECT_DESCRIPTION = 'project_description'
export const ISSUE_DATA = 'issue_data'
export const STATISTICS = 'statistics'
export const SCOPE = 'scope'
